name: Docker CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build dell’immagine Docker
      - name: Build Docker image
        run: docker build -t marcosorbini/ai_project:latest .

      # Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Push dell’immagine Docker
      - name: Push Docker image
        run: docker push marcosorbini/ai_project:latest
